### PR TITLE
Fixed and refactored graphic for Metric Results

### PR DESCRIPTION
**Pull request by danielkza**
Fixed graphic for Metric Results not displaying correctly

The graphic for Metric results previously did not have a set size.
Changed it so that it fills the whole space available, and made it
responsive to window resizing. That broke some particular cases of
histories with few changes and number of points that wasn't very small.

In addition, made the graphic display a single point instead of an
unhelpful messa

### CODE REVIEW

**Comment by rafamanzo** [comment]
Looks like a improvement.

We didn't notice the duplicated IDs betwwen the canvas and the span. As well the new style responsive and maximized looks great. Good catch :)

But I'm still not 100% sure about adding almost 35 new JS lines to the code:

* What do you think about, instead of using CSS styles like `loaded` using the controller response to hide the loader and display the canvas?
* By extracting `result_elm_id` generation to a helper we can benefit from easier unit tests. Let's do this?
* Can't we extract more JS code from the views to the class?

Nevertheless, this looks like a long discussion so I would like to know your opinion about extracting those refactorings into separate PRs, where we can discuss them isolated, and keep just the fix for graphic generation on this PR.

As well I would like to have @diegoamc, @marcheing and @pedroscocco opinions on these changes.

**Comment by danielkza** [comment]
> What do you think about, instead of using CSS styles like loaded using the controller response to hide the loader and display the canvas?

The idea is to avoid re-loading the graphic once it's already loaded. And, for example, if we're waiting for a processing, once it's done we can remove the loaded class and call display again so it refreshes.

> By extracting result_elm_id generation to a helper we can benefit from easier unit tests. Let's do this?

Good idea.

> Can't we extract more JS code from the views to the class?

The `<script>` tag we used directly in the view is there because it needs to be loaded only after the metric results HTML is loaded too. I didn't find a better way to do it, other than installing a global dynamic event, but I'll gladly accept other solutions :)

> Nevertheless, this looks like a long discussion so I would like to know your opinion about extracting those refactorings into separate PRs, where we can discuss them isolated, and keep just the fix for graphic generation on this PR.

Sure, but keep in mind some of the refactoring is actually necessary for things to work right. For example, I had to do the `loaded` thing because two instances of the graphic would be created sometimes if you opened and closed the graphic box multiple times. That's why I had to write a bit of code to store the graphic and chart objects in object properties.

**Comment by diegoamc** [comment]
I think you guys did a great job! Congratulations! :)

Regarding some aspects of the code: 

* @danielkza, the cache should prevent it from reloading, right? Maybe it isn't working the way intended. Do you think it's worth testing?
* I agree to extract `result_elm_id` to a helper method.

As the refactorings are linked with the bug fix, I'm afraid it is possible that we mess things up while trying to separate it into different PRs. If we feel the need to discuss this matters more, I think we can accept the PR and create issues with the labels `question` and `enhancement` about our reamaining doubts.

**Comment by danielkza** [comment]
> @danielkza, the cache should prevent it from reloading, right? Maybe it isn't working the way intended. Do you think it's worth testing?

The cache prevents us from re-generating the Javascript with the data for the same metric results. So if we load it multiple times (or if multiple people do it a different times) it will be cached in the server.

But in the same page, we don't even *need* to load it twice: once we have created the graphic, we can just hide it, and never bother setting it up or loading the Javascript again. That's what the `loaded` marker is for.

> As the refactorings are linked with the bug fix, I'm afraid it is possible that we mess things up while trying to separate it into different PRs. If we feel the need to discuss this matters more, I think we can accept the PR and create issues with the labels question and enhancement about our reamaining doubts.

Yeah, if I did things in separate from the start it would have been easier, but I ended up doing the refactoring *whilst* trying to fix the extra bugs that showed up after the original one. Like the one with the chart being created two times on top of one another. It's certainly not impossible to split things up now, but it would be a small bit of extra work. We can discuss that on the next work time.

**Comment by rafamanzo** [comment]
We need to talk in person about this before taking any action.

**Comment by diegoamc** [comment]
Does everybody reviewed this PR?
Will we extract the `result_elm_id` to a method before accepting it?

**Comment by rafamanzo** [comment]
I don't agree in merging it as it is for the reasons above.

We need to discuss improvements to it or split it into two PRs: one for
fixing the graph and add the tests that were supposed/ another for
refactorings.

Em qui, 11 de jun de 2015 às 15:27, Diego de Araújo Martinez Camarinha <
notifications@github.com> escreveu:

**Comment by danielkza** [comment]
I removed most of the refactoring and left only the most needed changes. We're still missing the JS tests though, but please take a loot at it until then.

**Comment by rafamanzo** [comment]
Thanks @danielkza it looks good for me now. Good job on preventing the chart from getting loaded several times and for your work on the HTML/CSS side of the metric results table.

**Comment by diegoamc** [comment]
Still, are we going to create unit tests before accepting it?

**Comment by rafamanzo** [comment]
I'm since 4pm trying to test Graphic with konacha.

It's a uncommon hard task unfortunately. I've made some progress by creating JS templates using EJS. The next step would be to add some mocks using sinon.js and what was described on https://coderwall.com/p/fm2ziw/jquery-chain-testing-with-sinonjs.

You can check my results in: https://github.com/mezuro/prezento/commit/48f1f9d40bb476dc9574b38796a0aeafff064133

Since it looks to be taking a long time to cover Graphic with tests, I suggest to continue from the new branch a new story for the next iteration.

Then we can merge this PR, which is a important bugfix.

**Pull request merged**
