### PR TITLE
Issue#219

### PR DESCRIPTION
**Pull request by EduardoBrasil**
solved Issue #219

### CODE REVIEW

**Comment by rafamanzo** [comment]
I am closing this due to inactivity. Please, reopen if you want to proceed with your PR.

**Comment by paulormm** [comment]
@vitorbaraujo and @dylanguedes, please see this PR and think about if the MES'2017 team should proceed with this one.

**Comment by DylanGuedes** [comment]
Hmm, I think that starting from scratch with rails_admin will be better for them, overall (mainly because of possible API changes).

**Comment by rafamanzo** [comment]
Just be careful with rails_admin, as we don't have standard ActiveModel classes. Have a look at ActiveAdmin which provides more flexibility.

**Pull request closed without merging**
