### PR TITLE
Fix backwards compatibility

### PR DESCRIPTION
**Pull request by dread-uo**

### CODE REVIEW

**Comment by rafamanzo** [comment]
Nice catch. Is there an Travis build failed for this reason?

**Comment by diegoamc** [comment]
But why do we want to support ruby 2.0.0-p59**4**? CentOS' ruby version is 2.0.0-p59**8**.

Also, I believe the previous code had been already adapted to work on the CentOS version, as the comment said. Is that code failing for version 2.1.5?

**Comment by dread-uo** [comment]
Yes, [this](https://travis-ci.org/mezuro/prezento/jobs/126204899) build was failing for this reason.
@diegoamc, sorry, I may have mistyped it :stuck_out_tongue_closed_eyes:; but the build above failed for ruby 2.0.0-p598.

Though this worked locally, we get timeouts on Travis. Do you think it could be this alteration?

**Comment by diegoamc** [comment]
I think that modification (which put the comment) fixed the build you are referring to, @dread-uo.

Note that the build is from this commit: https://github.com/mezuro/prezento/commit/cb40650003dd9ef0de905e2833ff66afb9c43b2e

If you browse the code using that commit as the HEAD, you'll see that that file used a fancy ruby syntax: https://github.com/mezuro/prezento/blob/cb40650003dd9ef0de905e2833ff66afb9c43b2e/features/support/header.rb

That was fixed afterwards by this [commit](https://github.com/mezuro/prezento/commit/4b8f3ae44e26fa4b81895fe7a24d4b9e9435e71e) which, in turn, was part of [this PR](https://github.com/mezuro/prezento/pull/353). As you can see there, all checks were successful before it was accepted. :smile:

**Comment by rafamanzo** [comment]
Still how does this build passes? https://travis-ci.org/mezuro/prezento/builds/132892500

Maybe the fail you mentioned has been fixed indirectly. Do you think this MR is still necessary?

**Comment by diegoamc** [comment]
I'm the fastest gun in all Mezuro's organization, @rafamanzo :gun:

**Comment by dread-uo** [comment]
I got confused by all those failing/passing builds, sorry for that! Anyway, it seems like both ways work. If you choose to use this PR's syntax, we can change the commit message. I won't be sad if you choose to simply close this either, as the builds are ok without it.

**Comment by rafamanzo** [comment]
I agree your syntax is clearer. Could you just restore the comment?

**Pull request merged**
