### PR TITLE
Removing 'back' buttons

### PR DESCRIPTION
**Pull request by cambraia**
Removing back buttons and its locales, from the issue #390 from mezuro/prezento.

### CODE REVIEW

**Comment by diegoamc** [comment]
Thanks for the contribution, @cambraia.

It seems the acceptance tests need some updates. Could you please fix them?

**Comment by cambraia** [comment]
@diegoamc I am having doubts related to the relevance of those tests.Those tests were testing the back button link, now that this button is gone, is it relevant to test the act of going back to the previous window in these scenarios?

**Comment by cambraia** [comment]
@diegoamc I removed the outdated acceptance tests and now Travis build is broken due to unrelated errors.

**Comment by vitorbaraujo** [comment]
How is the current status of this PR? What can be done?

**Pull request closed without merging**
