### PR TITLE
Take full advantage of Travis' infrastructure

### PR DESCRIPTION
**Pull request by rafamanzo**
We are currently running one full build for each Ruby version only 3 concurrent jobs. By my observations we can go as high as 5 concurrent jobs with Travis.

This first separates each test level into its own job. As cucumber tests are really heavy, they got splat into other 4 builds thus 6 separate builds for each Ruby. Previous to this builds were taking around 40min. The build for the last push took 18min.

Also the bundler cache has been enabled. Notice that there is one failling acceptance test that is not related to any known change on prezento (started here: https://travis-ci.org/mezuro/prezento/builds/157062540). This also was one of my attempts on fixing it as it could be blamed by build timeouts (my next attempt will try to revert the version of kalibro used for these tests).

### CODE REVIEW

**Comment by rafamanzo** [comment]
ping @mezuro/core

**Comment by dread-uo** [comment]
That's really nice!
But that error persists. Might it be that this multi VM setup impacts the performance of tests? Then it would make some sense for that specific test not to pass.

**Comment by rafamanzo** [comment]
From the description: "Notice that there is one failling acceptance test that is not related to any known change on prezento (started here: https://travis-ci.org/mezuro/prezento/builds/157062540). This also was one of my attempts on fixing it as it could be blamed by build timeouts (my next attempt will try to revert the version of kalibro used for these tests)."

The error is prior to this. This was a wild guess on trying to fixing it that turned to a nice feature. As stated there, the next attempt will be on reverting KalibroProcessor's version.

**Comment by dread-uo** [comment]
Oh, sorry; I thought it happened the other way :)
In my opinion, this PR can be accepted. I think I don't have permission for that, though.
Anyway, it would be nice if the other people from @mezuro/core had a glimpse at this travis magic.

**Pull request merged**
