### PR TITLE
Changes 'kalibro_errors' to use 'likeno_errors'

### PR DESCRIPTION
**Pull request by DylanGuedes**
The change fixes deprecated warnings about "prezento_errors".

### CODE REVIEW

**Comment by rafamanzo** [comment]
Nice! :trophy: 

Can you add an entry about this to the CHANGELOG?

**Comment by DylanGuedes** [comment]
Sure! Added an entry on the changelog based on the 'semver' conventions.

**Comment by rafamanzo** [comment]
It actually goes under unreleased :)

**Comment by DylanGuedes** [comment]
Haha fixed. I though that the releases below were all unreleased.

**Pull request merged**
